services:
  - type: web
    name: image-caption-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
